#106 Update docs base image
Old node image was exiting with status 139 (Segmentation Fault) and was trying to use all memory.
Stack trace below:

```
==== JS stack trace =========================================

    0: ExitFrame [pc: 0x564c5d211d19]
Security context: 0x1803bec808d1 <JSObject>
    1: /* anonymous */ [0x3e404e2bfe29] [/home/node/node_modules/colors/safe.js:~1] [pc=0x3b2322b927f4](this=0x3e404e2bff21 <Object map = 0x23fe830c0439>,0x3e404e2bff21 <Object map = 0x23fe830c0439>,0x3e404e2bfee1 <JSFunction require (sfi = 0x18e522cd8051)>,0x3e404e2bfe89 <Module map = 0x23fe830fbf39>,0x0865e16db1d9 <String[#38]: /home/node/node_modules/colo...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```